[tox]
envlist = clean,py39,flake8,report,py39-black,docs

skipsdist = True

[flake8]
description = Run flake8 on Python code
ignore = E226,E302,E41
exclude = .git,__pycache__,docs/source/conf.py,old,build,dist
max-complexity = 10

[base]
setenv =
    DJANGO_SETTINGS_MODULE=pdm.settings.local
    PYTHONPATH={toxinidir}


[testenv]
description = Run tox test
passenv =
    SECRET_KEY
    DEBUG
    ALLOWED_HOSTS
    DATABASE_URL
deps = -r{toxinidir}/requirements/local.txt
    
commands =
    django-admin test
    coverage run  manage.py test

setenv = 
    {[base]setenv}

[testenv:py36-black]
description = Run Python 3.6 with black
deps =
    black
commands =
    black --check --diff pdm


[testenv:report]
description = Generate coverage report
skip_empty = true
deps = coverage
skip_install = true
commands =
    coverage report 
    coverage html


[testenv:flake8]
description = Run flake8
deps=flake8
commands=flake8 library --exit-zero


[testenv:docs]
description = Invoke sphinx-build to build the HTML docs
changedir = docs
allowlist_externals = make
deps =
    Sphinx
    Django
commands =
    make clean
    make html

[testenv:clean]
description = Clean up the virtualenv
deps = coverage
skip_install = true
commands = coverage erase









