# Generated by Django 4.0 on 2022-01-23 12:31

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0001_initial'),
        ('demographics', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Crop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Farmer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('id_no', models.CharField(max_length=100, null=True)),
                ('phone_no', models.CharField(max_length=15, null=True)),
                ('crops', models.ManyToManyField(blank=True, to='farmers.Crop')),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='authentication.user')),
                ('village', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='demographics.village')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
