# Generated by Django 4.0 on 2022-01-26 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('farmers', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='farmer',
            name='id_no',
        ),
        migrations.RemoveField(
            model_name='farmer',
            name='phone_no',
        ),
    ]
