# Generated by Django 3.2.11 on 2022-01-27 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmers', '0002_remove_farmer_id_no_remove_farmer_phone_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farmer',
            name='crops',
            field=models.ManyToManyField(blank=True, null=True, to='farmers.Crop'),
        ),
    ]
