# Generated by Django 4.0 on 2022-01-29 17:10

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('farmers', '0003_alter_farmer_crops'),
    ]

    operations = [
        migrations.CreateModel(
            name='Produce',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('produce_in', models.CharField(choices=[('sold', 'sold'), ('market', 'market'), ('storage', 'storage')], max_length=10)),
                ('value', models.DecimalField(decimal_places=2, max_digits=15)),
                ('crop', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='farmers.crop')),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='farmers.farmer')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
