# Generated by Django 4.0 on 2022-01-29 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmers', '0004_produce'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farmer',
            name='crops',
            field=models.ManyToManyField(blank=True, to='farmers.Crop'),
        ),
    ]
