# Generated by Django 4.0.2 on 2022-02-06 09:47

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('demographics', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PillarProgram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('name', models.CharField(max_length=250)),
                ('description', models.TextField(null=True)),
                ('start_year', models.DateField(blank=True, null=True)),
                ('available_funds', models.FloatField(default=0.0)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PublicSector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=10)),
                ('available_funds', models.FloatField(default=0.0)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='VillageDisbursement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('amount', models.FloatField()),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('DISBURSED', 'Disbursed')], default='PENDING', max_length=50)),
                ('pillar_program', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='pillar_management.pillarprogram')),
                ('public_sector', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='pillar_management.publicsector')),
                ('village', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='demographics.village')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SubCountyDisbursement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('amount', models.FloatField()),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('DISBURSED', 'Disbursed')], default='PENDING', max_length=50)),
                ('pillar_program', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='pillar_management.pillarprogram')),
                ('public_sector', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='pillar_management.publicsector')),
                ('subcounty', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='demographics.subcounty')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PublicSectorDisbursement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('amount', models.FloatField()),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('DISBURSED', 'Disbursed')], default='PENDING', max_length=50)),
                ('pillar_program', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='pillar_management.pillarprogram')),
                ('public_sector', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='pillar_management.publicsector')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PillarProgramDisbursement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('amount', models.FloatField()),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('DISBURSED', 'Disbursed')], default='PENDING', max_length=50)),
                ('pillar_program', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='pillar_management.pillarprogram')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ParishDisbursement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('amount', models.FloatField()),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('DISBURSED', 'Disbursed')], default='PENDING', max_length=50)),
                ('parish', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='demographics.parish')),
                ('pillar_program', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='pillar_management.pillarprogram')),
                ('public_sector', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='pillar_management.publicsector')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DistrictDisbursement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('amount', models.FloatField()),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('DISBURSED', 'Disbursed')], default='PENDING', max_length=50)),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='demographics.district')),
                ('pillar_program', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='pillar_management.pillarprogram')),
                ('public_sector', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='pillar_management.publicsector')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CountyDisbursement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('amount', models.FloatField()),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('DISBURSED', 'Disbursed')], default='PENDING', max_length=50)),
                ('county', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='demographics.county')),
                ('pillar_program', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='pillar_management.pillarprogram')),
                ('public_sector', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='pillar_management.publicsector')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
