# Generated by Django 4.0 on 2022-01-23 12:31

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pillar_management', '0001_initial'),
        ('farmers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Evoucher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('voucher_no', models.CharField(max_length=200, null=True)),
                ('value', models.DecimalField(decimal_places=2, max_digits=15)),
                ('farm_input', models.TextField(null=True)),
                ('beneficiary', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='farmers.farmer')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PSPMPillarProgram',
            fields=[
                ('pillarprogram_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='pillar_management.pillarprogram')),
                ('evouchers', models.ManyToManyField(blank=True, to='production_storage_processing_marketing.Evoucher')),
                ('farmers', models.ManyToManyField(blank=True, to='farmers.Farmer')),
            ],
            options={
                'abstract': False,
            },
            bases=('pillar_management.pillarprogram',),
        ),
    ]
