# Generated by Django 4.0.2 on 2022-02-06 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demographics', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='county',
            name='available_funds',
            field=models.JSONField(default={'total_funds_available': 0}),
        ),
        migrations.AlterField(
            model_name='district',
            name='available_funds',
            field=models.JSONField(default={'total_funds_available': 0}),
        ),
        migrations.AlterField(
            model_name='parish',
            name='available_funds',
            field=models.JSONField(default={'total_funds_available': 0}),
        ),
        migrations.AlterField(
            model_name='subcounty',
            name='available_funds',
            field=models.JSONField(default={'total_funds_available': 0}),
        ),
        migrations.AlterField(
            model_name='village',
            name='available_funds',
            field=models.JSONField(default={'total_funds_available': 0}),
        ),
    ]
