# Generated by Django 4.0.2 on 2022-02-02 17:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('demographics', '0002_alter_county_name_alter_district_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='county',
            name='district',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='counties', to='demographics.district'),
        ),
        migrations.AlterField(
            model_name='parish',
            name='sub_county',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parishes', to='demographics.subcounty'),
        ),
        migrations.AlterField(
            model_name='subcounty',
            name='county',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_counties', to='demographics.county'),
        ),
        migrations.AlterField(
            model_name='village',
            name='parish',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='villages', to='demographics.parish'),
        ),
    ]
