# Generated by Django 4.0.2 on 2022-02-06 09:47

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('demographics', '0001_initial'),
        ('farmers', '0001_initial'),
        ('production_storage_processing_marketing', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MindSetChampion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('name', models.CharField(max_length=200, null=True)),
                ('phone', models.CharField(max_length=200, null=True)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='demographics.district')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EconomicEnhancementSupport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('budget_spend', models.DecimalField(decimal_places=2, max_digits=15, null=True)),
                ('farmers', models.ManyToManyField(blank=True, to='farmers.Farmer')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CommunityMobilization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('budget_spend', models.DecimalField(decimal_places=2, max_digits=15, null=True)),
                ('evouchers', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='production_storage_processing_marketing.evoucher')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
