# Generated by Django 4.0 on 2022-01-29 18:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('farmers', '0004_produce'),
        ('mindset_change', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='economicenhancementsupport',
            name='farmers',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='farmers.farmer'),
            preserve_default=False,
        ),
    ]
