# Generated by Django 4.0 on 2022-01-29 18:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demographics', '0001_initial'),
        ('mindset_change', '0002_alter_economicenhancementsupport_farmers'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MidSetChampion',
            new_name='MindSetChampion',
        ),
    ]
