# Generated by Django 4.0 on 2022-01-23 12:34

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pillar_management', '0001_initial'),
        ('demographics', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinancialInclusionPillar',
            fields=[
                ('pillarprogram_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='pillar_management.pillarprogram')),
            ],
            options={
                'abstract': False,
            },
            bases=('pillar_management.pillarprogram',),
        ),
        migrations.CreateModel(
            name='Initiative',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='OrganizationType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='CommunityOrganization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('name', models.CharField(max_length=100)),
                ('key_personel', models.CharField(max_length=250)),
                ('contact', models.CharField(max_length=15)),
                ('organization_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='financial_inclusion.organizationtype')),
                ('village', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='demographics.village')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BusinessDevelopmentService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('budget_spend', models.DecimalField(decimal_places=2, max_digits=15, null=True)),
                ('attendance', models.IntegerField(null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('topic', models.TextField(blank=True, null=True)),
                ('initiative', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='financial_inclusion.initiative')),
                ('village', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='demographics.village')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
