# Generated by Django 4.0.2 on 2022-02-06 09:47

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('demographics', '0001_initial'),
        ('farmers', '0001_initial'),
        ('pillar_management', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessDevelopmentService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('budget_spend', models.DecimalField(decimal_places=2, max_digits=15, null=True)),
                ('attendance', models.IntegerField(null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('topic', models.TextField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CommunityOrganization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('name', models.CharField(max_length=100)),
                ('key_personel', models.CharField(max_length=250)),
                ('contact', models.CharField(max_length=15)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Initiative',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='OrganizationType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Saving',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('amount', models.FloatField()),
                ('farmer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='farmers.farmer')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FinancialInclusionPillar',
            fields=[
                ('pillarprogram_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='pillar_management.pillarprogram')),
                ('beneficiaries', models.ManyToManyField(blank=True, to='financial_inclusion.CommunityOrganization')),
                ('trainings', models.ManyToManyField(blank=True, to='financial_inclusion.BusinessDevelopmentService')),
            ],
            options={
                'abstract': False,
            },
            bases=('pillar_management.pillarprogram',),
        ),
        migrations.AddField(
            model_name='communityorganization',
            name='organization_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='financial_inclusion.organizationtype'),
        ),
        migrations.AddField(
            model_name='communityorganization',
            name='village',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='demographics.village'),
        ),
        migrations.AddField(
            model_name='businessdevelopmentservice',
            name='initiative',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='financial_inclusion.initiative'),
        ),
        migrations.AddField(
            model_name='businessdevelopmentservice',
            name='village',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='demographics.village'),
        ),
    ]
