# Generated by Django 4.0.2 on 2022-02-07 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial_inclusion', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessdevelopmentservice',
            name='budget_spend',
            field=models.FloatField(null=True),
        ),
    ]
