# Generated by Django 4.0 on 2022-01-29 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial_inclusion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='financialinclusionpillar',
            name='beneficiaries',
            field=models.ManyToManyField(blank=True, to='financial_inclusion.CommunityOrganization'),
        ),
        migrations.AddField(
            model_name='financialinclusionpillar',
            name='trainings',
            field=models.ManyToManyField(blank=True, to='financial_inclusion.BusinessDevelopmentService'),
        ),
    ]
