# Generated by Django 4.0.2 on 2022-02-02 21:46

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('farmers', '0005_alter_farmer_crops'),
        ('financial_inclusion', '0002_financialinclusionpillar_beneficiaries_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Saving',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('amount', models.FloatField()),
                ('farmer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='farmers.farmer')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
