# Generated by Django 4.0 on 2022-01-29 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmers', '0005_alter_farmer_crops'),
        ('mind_set_change', '0003_rename_midsetchampion_mindsetchampion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='economicenhancementsupport',
            name='farmers',
        ),
        migrations.AddField(
            model_name='economicenhancementsupport',
            name='farmers',
            field=models.ManyToManyField(blank=True, to='farmers.Farmer'),
        ),
    ]
